name: kirbykleeberg
favicon: null
layout_spectrum: 0.009800938423722982
typography_spectrum: 0.07286777906119823
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f2e3d0'
    - '#989687'
    - '#241c33'
    - '#655266'
    - '#e29bad'
  brandStrength: 0.25
  lightness: 0.3125
  saturation: 0
  rhythmicContrast: 1
purpose: []
