name: kirbykleeberg
favicon: null
layout_spectrum: 0.009800938423722982
typography_spectrum: 0.07286777906119823
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.3866312864702195
  lightness: 0.8590940476860851
  saturation: 0.1695217457599938
  rhythmicContrast: 0.6937111674342304
purpose: []
